"""body_length_fixed

Revision ID: 95833754c33c
Revises: e91ea9521ecf
Create Date: 2020-07-03 23:13:27.386055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95833754c33c'
down_revision = 'e91ea9521ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('bodys', sa.String(length=10000), nullable=True))
    op.drop_column('post', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', mysql.VARCHAR(length=8000), nullable=True))
    op.drop_column('post', 'bodys')
    # ### end Alembic commands ###
