"""body_type_fixed

Revision ID: beb28a5c883a
Revises: 95833754c33c
Create Date: 2020-07-03 23:24:30.640633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'beb28a5c883a'
down_revision = '95833754c33c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.TEXT(), nullable=True))
    op.drop_column('post', 'bodys')
    op.drop_column('post', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('category', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('bodys', mysql.VARCHAR(length=10000), nullable=True))
    op.drop_column('post', 'body')
    # ### end Alembic commands ###
