"""category_fixed

Revision ID: e91ea9521ecf
Revises: 00beeaac91d9
Create Date: 2020-07-03 23:05:40.218645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e91ea9521ecf'
down_revision = '00beeaac91d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('post_ibfk_2', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'category', ['category_id'], ['id'])
    op.drop_column('post', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('category', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_ibfk_2', 'post', 'category', ['category'], ['id'])
    op.drop_column('post', 'category_id')
    # ### end Alembic commands ###
